<?php
if ( ! defined( 'ABSPATH' ) ) exit;
add_settings_field(
  'wpesd-check-products-taxo-widget',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
// Taxos label check
add_settings_field(
  'wpesd-checkout-page-check',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-thankyou-page-check',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-orderdate-thankyou-page-check',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
// controls
// *** estimass
add_settings_field(
  'wpesd-estimass-color',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimass-fontsize',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimass-fontweight',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimass-fontfamilly',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimdate-color',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-reason-color',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-reason-fontsize',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-reason-fontweight',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-reason-fontfamilly',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
// *** dimensions
add_settings_field(
  'wpesd-estimdate-fontsize',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimdate-fontweight',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);
add_settings_field(
  'wpesd-estimdate-fontfamilly',
  '',
  'wpesd_plugin_function_for_datas_callback',
  'wpesd-plugin-main-menu',
  'wpesd-plugin-switch-section'
);

// Register Settings all
register_setting(
  'wpesd-plugin-settings', 
  'wpesd-check-products-taxo-widget' 
);
// Taxos label check
register_setting(
  'wpesd-plugin-settings', 
  'wpesd-checkout-page-check' 
);
register_setting(
  'wpesd-plugin-settings', 
  'wpesd-thankyou-page-check' 
);
register_setting(
  'wpesd-plugin-settings', 
  'wpesd-orderdate-thankyou-page-check' 
);
// controls
// *** estimass
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimass-color'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimass-fontsize'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimass-fontweight'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimass-fontfamilly'
);
// *** estimdate
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimdate-color'
);
// *** reason
register_setting(
  'wpesd-plugin-settings',
  'wpesd-reason-color'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-reason-fontsize'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-reason-fontweight'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-reason-fontfamilly'
);
// *** estimdate
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimdate-fontsize'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimdate-fontweight'
);
register_setting(
  'wpesd-plugin-settings',
  'wpesd-estimdate-fontfamilly'
);
